"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  # Plugins
  # Smart Enter
  { on = "l", run = ["plugin smart-enter"], desc = "Enter the child directory, or open the file" },
  { on = "<Right>", run = ["plugin smart-enter"], desc = "Enter the child directory, or open the file" },
  # What Size
  { on = ["<A-s>"], run = "plugin what-size", desc = "Calc size of selection or cwd" },
  # Max-Preview
  { on = ["M"], run = "plugin toggle-pane max-preview", desc = "Maximize or restore preview" },

  # Hopping
  { on = ["K"], run = "arrow -5", desc = "Move cursor up 5 lines" },
  { on = ["J"], run = "arrow 5", desc = "Move cursor down 5 lines" },
  { on = ["<S-Up>"], run = "arrow -5", desc = "Move cursor up 5 lines" },
  { on = ["<S-Down>"], run = "arrow 5", desc = "Move cursor down 5 lines" },

  # Seeking
  { on = ["<C-k>"], run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = ["<C-j>"], run = "seek 5", desc = "Seek down 5 units in the preview" },
  { on = ["<C-Up>"], run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = ["<C-Down>"], run = "seek 5", desc = "Seek down 5 units in the preview" },

  # Go To
  { on = ["g", "."], run = "cd ~/.dotfiles/", desc = "the dotfiles directory" },
  { on = ["g", "C"], run = "cd '~/Stuff/College Stuff/OU/'", desc = "the OU directory" },
  { on = ["g", "D"], run = "cd ~/Stuff/Documents/", desc = "the documents directory" },
  { on = ["g", "P"], run = "cd ~/Stuff/LaTeX/Applications/PhD 2025/", desc = "the PhD directory" },
  { on = ["g", "T"], run = "cd ~/Stuff/Documents/Tickets/", desc = "the trash directory" },
  { on = ["g", "V"], run = "cd ~/Stuff/Notes/", desc = "the Notes directory" },
  { on = ["g", "W"], run = "cd ~/Stuff/Websites/", desc = "the websites directory" },
  { on = ["g", "b"], run = "cd ~/Stuff/Books/", desc = "the Books directory" },
  { on = ["g", "c"], run = "cd ~/.config/", desc = "the config directory" },
  { on = ["g", "d"], run = "cd ~/Downloads/", desc = "the downloads directory" },
  { on = ["g", "h"], run = "cd ~", desc = "the home directory" },
  { on = ["g", "l"], run = "cd ~/Stuff/LaTeX/", desc = "the LaTeX directory" },
  { on = ["g", "m"], run = "cd /run/media/$USER", desc = "the mount directory" },
  { on = ["g", "n"], run = "cd ~/.config/nvim/", desc = "the neovim config directory" },
  { on = ["g", "p"], run = "cd ~/Stuff/Pictures/", desc = "the Pictures directory" },
  { on = ["g", "s"], run = "cd ~/Stuff/", desc = "the Stuff directory" },
  { on = ["g", "t"], run = "cd ~/.local/share/Trash/files/", desc = "the trash directory" },
  { on = ["g", "v"], run = "cd ~/Stuff/Videos/", desc = "the Videos directory" },
  { on = ["g", "w"], run = "cd ~/Stuff/Websites/ojasb.xyz", desc = "my website" },

  # Toggle
  { on = ["<C-Space>"], run = ["toggle", "arrow -1"], desc = "Toggle the current selection state" },

  # Operation
  { on = ["R"], run = "rename --empty=stem --cursor=start", desc = "Rename a file and wait to paste a copied value" },
  { on = ["<C-s>"], run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },

]
