[misc]
pre_sudo = true
disable = ["git_repos"]
assume_yes = true
cleanup = true
ignore_failures = ["custom_commands"]

[commands]
"Yazi Packages" = "ya pack -u"
"Passwords" = "cd ~/.keepass; git pull --rebase --autostash; git add .; oco || exit"
"Dotfiles" = "cd ~/.dotfiles; git pull --rebase --autostash; git add .; oco || exit"
"Neovim Config" = "cd ~/.config/nvim; git pull --rebase --autostash; git add .; oco || exit"
