[misc]
pre_sudo = true
disable = ["git_repos"]
assume_yes = true
cleanup = true
ignore_failures = ["custom_commands"]

[commands]
"Passwords" = "cd ~/.keepass; git pull --rebase --autostash; git add .; oco"
"Dotfiles" = "ya pack -u; cd ~/.config/nvim/; git pull --rebase --autostash; git add .; oco; cd ~/.dotfiles/; git pull --rebase --autostash; git add .; oco"
